In [1]:
!pip install langgraph langchain-openai fastapi uvicorn python-dotenv aiosqlite sqlalchemy pydantic streamlit --quiet

print("All required packages installed successfully!")

All required packages installed successfully!

In [2]:
!pip install langgraph pandas

Requirement already satisfied: langgraph in c:\users\rajoo\anaconda3\lib\site-packages (1.1.8)
Requirement already satisfied: pandas in c:\users\rajoo\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: langchain-core<2,>=1.3.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langgraph) (1.3.0)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langgraph) (4.0.2)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.9 in c:\users\rajoo\anaconda3\lib\site-packages (from langgraph) (1.0.10)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langgraph) (0.3.13)
Requirement already satisfied: pydantic>=2.7.4 in c:\users\rajoo\anaconda3\lib\site-packages (from langgraph) (2.10.3)
Requirement already satisfied: xxhash>=3.5.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langgraph) (3.6.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langchain-core<2,>=1.3.0->langgraph) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\users\rajoo\anaconda3\lib\site-packages (from langchain-core<2,>=1.3.0->langgraph) (0.7.32)
Requirement already satisfied: packaging>=23.2.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langchain-core<2,>=1.3.0->langgraph) (24.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langchain-core<2,>=1.3.0->langgraph) (6.0.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langchain-core<2,>=1.3.0->langgraph) (9.0.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langchain-core<2,>=1.3.0->langgraph) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langchain-core<2,>=1.3.0->langgraph) (0.14.1)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\rajoo\anaconda3\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2,>=1.3.0->langgraph) (2.1)
Requirement already satisfied: ormsgpack>=1.12.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in c:\users\rajoo\anaconda3\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph) (0.28.1)
Requirement already satisfied: orjson>=3.11.5 in c:\users\rajoo\anaconda3\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.3.0->langgraph) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.3.0->langgraph) (2.32.3)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\rajoo\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.3.0->langgraph) (0.23.0)
Requirement already satisfied: anyio in c:\users\rajoo\anaconda3\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (4.7.0)
Requirement already satisfied: certifi in c:\users\rajoo\anaconda3\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\rajoo\anaconda3\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (1.0.9)
Requirement already satisfied: idna in c:\users\rajoo\anaconda3\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\rajoo\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\rajoo\anaconda3\lib\site-packages (from pydantic>=2.7.4->langgraph) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\rajoo\anaconda3\lib\site-packages (from pydantic>=2.7.4->langgraph) (2.27.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rajoo\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rajoo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rajoo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rajoo\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\rajoo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\rajoo\anaconda3\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.3.0->langgraph) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rajoo\anaconda3\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.3.0->langgraph) (2.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\rajoo\anaconda3\lib\site-packages (from anyio->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (1.3.0)

In [3]:
!pip install nest_asyncio

Requirement already satisfied: nest_asyncio in c:\users\rajoo\anaconda3\lib\site-packages (1.6.0)

In [11]:
from langgraph.graph import StateGraph, END
from typing import TypedDict, List

In [12]:
class AgentState(TypedDict):
    resume_text: str
    ats_score: int
    stage: str
    interview_qa: List[dict]
    screening: dict
    meeting_link: str

In [13]:
def ats_agent(state):
    resume = state["resume_text"]
    
    score = 0
    if "Python" in resume:
        score += 40
    if "FastAPI" in resume:
        score += 40
    if "SQL" in resume:
        score += 20
    
    state["ats_score"] = score
    state["stage"] = "interview" if score >= 80 else "rejected"
    
    return state

In [14]:
def interview_agent(state):
    questions = [
        "What is Python?",
        "Explain FastAPI",
        "What is API?"
    ]
    
    qa = []
    
    for q in questions:
        answer = "demo answer"
        score = 8
        
        qa.append({
            "question": q,
            "answer": answer,
            "score": score
        })
    
    state["interview_qa"] = qa
    state["stage"] = "screening"
    
    return state

In [15]:
def screening_agent(state):
    state["screening"] = {
        "notice_period": "30 days",
        "joining": "Immediate"
    }
    
    state["stage"] = "scheduled"
    
    return state

In [16]:
def scheduling_agent(state):
    state["meeting_link"] = "https://meet.google.com/demo"
    return state

In [17]:
graph = StateGraph(AgentState)

graph.add_node("ats", ats_agent)
graph.add_node("interview", interview_agent)
graph.add_node("screening", screening_agent)
graph.add_node("schedule", scheduling_agent)

graph.set_entry_point("ats")

graph.add_edge("ats", "interview")
graph.add_edge("interview", "screening")
graph.add_edge("screening", "schedule")
graph.add_edge("schedule", END)

recruitment_graph = graph.compile()

In [18]:
result = recruitment_graph.invoke({
    "resume_text": "I know Python FastAPI SQL"
})

print(result)

{'resume_text': 'I know Python FastAPI SQL', 'ats_score': 100, 'stage': 'scheduled', 'interview_qa': [{'question': 'What is Python?', 'answer': 'demo answer', 'score': 8}, {'question': 'Explain FastAPI', 'answer': 'demo answer', 'score': 8}, {'question': 'What is API?', 'answer': 'demo answer', 'score': 8}], 'screening': {'notice_period': '30 days', 'joining': 'Immediate'}, 'meeting_link': 'https://meet.google.com/demo'}

In [19]:
import pandas as pd

db = pd.DataFrame(columns=[
    "resume", "ats_score", "stage"
])

In [20]:
db.loc[len(db)] = [
    result["resume_text"],
    result["ats_score"],
    result["stage"]
]

db

                      resume  ats_score      stage
0  I know Python FastAPI SQL        100  scheduled

In [21]:
print("HR DASHBOARD")
print(db)

HR DASHBOARD
                      resume  ats_score      stage
0  I know Python FastAPI SQL        100  scheduled

In [22]:
# Filter shortlisted
db[db["stage"] == "scheduled"]

                      resume  ats_score      stage
0  I know Python FastAPI SQL        100  scheduled

In [23]:
def hr_chatbot(query):
    
    if "all candidates" in query:
        return db
    
    if "selected" in query:
        return db[db["stage"] == "scheduled"]
    
    if "rejected" in query:
        return db[db["stage"] == "rejected"]
    
    return "No data found"

In [24]:
hr_chatbot("show all candidates")

                      resume  ats_score      stage
0  I know Python FastAPI SQL        100  scheduled

In [25]:
def role_summary():
    return {
        "total_candidates": len(db),
        "selected": len(db[db["stage"] == "scheduled"]),
        "rejected": len(db[db["stage"] == "rejected"])
    }

role_summary()

{'total_candidates': 1, 'selected': 1, 'rejected': 0}

In [26]:
def full_demo():
    resume = "I know Python FastAPI SQL"
    
    result = recruitment_graph.invoke({
        "resume_text": resume
    })
    
    print("Pipeline Output:", result)
    
    # Save
    db.loc[len(db)] = [
        result["resume_text"],
        result["ats_score"],
        result["stage"]
    ]
    
    print("\nDashboard:")
    print(db)
    
    print("\nChatbot Query:")
    print(hr_chatbot("show all candidates"))

In [27]:
full_demo()

Pipeline Output: {'resume_text': 'I know Python FastAPI SQL', 'ats_score': 100, 'stage': 'scheduled', 'interview_qa': [{'question': 'What is Python?', 'answer': 'demo answer', 'score': 8}, {'question': 'Explain FastAPI', 'answer': 'demo answer', 'score': 8}, {'question': 'What is API?', 'answer': 'demo answer', 'score': 8}], 'screening': {'notice_period': '30 days', 'joining': 'Immediate'}, 'meeting_link': 'https://meet.google.com/demo'}

Dashboard:
                      resume  ats_score      stage
0  I know Python FastAPI SQL        100  scheduled
1  I know Python FastAPI SQL        100  scheduled

Chatbot Query:
                      resume  ats_score      stage
0  I know Python FastAPI SQL        100  scheduled
1  I know Python FastAPI SQL        100  scheduled

In [28]:
db

                      resume  ats_score      stage
0  I know Python FastAPI SQL        100  scheduled
1  I know Python FastAPI SQL        100  scheduled

In [29]:
hr_chatbot("show all candidates")

                      resume  ats_score      stage
0  I know Python FastAPI SQL        100  scheduled
1  I know Python FastAPI SQL        100  scheduled